### ISSUE TITLE
Update Contact Page

### ISSUE THREAD

**Issue by malgorzataf** [fathomlondon/fath.om#412]
## Current Behaviour

-

## Expected Behaviour

- Add image and illustration to the existing page, file available here: https://www.dropbox.com/s/my0xh7oo3pxm9nh/Fathom_Website%20-%20final.sketch?dl=0

## Steps to Reproduce

1.

## Screenshots / Screen Recordings
![screen shot 2018-11-06 at 16 49 21](https://user-images.githubusercontent.com/35142781/48079779-fcce3b80-e1e3-11e8-8a33-66a9dcf58e2b.png)

-
[](url)

**Comment by ibrennan** [comment]
Old designs now, closing
